# Generated by Django 4.2.5 on 2023-09-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderName', models.CharField(max_length=50)),
                ('folderDesc', models.CharField(max_length=255)),
                ('parentFolderId', models.IntegerField()),
                ('folderUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTitle', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriveApp.folder')),
            ],
        ),
    ]
