# Generated by Django 4.2.5 on 2023-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parentFolderId',
            field=models.IntegerField(null=True),
        ),
    ]
